name: example

on: 
  push:

jobs:

  build: 
    runs-on: ${{matrix.os}} 
    strategy: 
      fail-fast: false
      matrix: 
        os: [ubuntu-20.04, macos-latest, windows-latest]
        java: [ '8', '11', '17']
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - run: mvn test
